# Default configuration for reverse Game of Life solver
# This uses CaDiCaL solver with balanced settings

simulation:
  generations: 5
  boundary_condition: "dead"  # "dead", "wrap", "mirror"

solver:
  max_solutions: 1
  timeout_seconds: 43200 #12 hours
  num_threads: null  # Use available parallelism by default
  enable_preprocessing: true
  verbosity: 1  # 0=quiet, 1=normal, 2=verbose
  backend: "parkissat"  # "cadical", "parkissat"

input:
  target_state_file: "input/target_states/glider.txt"
  
output:
  format: "text"  # "text", "json", "visual"
  save_intermediate: false
  output_directory: "output/solutions"

encoding:
  symmetry_breaking: false