# CaDiCaL solver configuration with balanced settings
# Good for general-purpose solving with moderate performance

simulation:
  generations: 5
  boundary_condition: "dead"

solver:
  max_solutions: 1
  timeout_seconds: 300
  num_threads: 1  # CaDiCaL is single-threaded
  enable_preprocessing: true
  verbosity: 1  # Show some progress information
  backend: "cadical"

input:
  target_state_file: "input/target_states/example.txt"
  
output:
  format: "text"
  save_intermediate: false
  output_directory: "output/solutions"

encoding:
  symmetry_breaking: false